setup:

	rm -rf globe;       mkdir globe;
	rm -rf globe/css;   mkdir globe/css;
	rm -rf globe/fonts; mkdir globe/fonts;
	rm -rf globe/jpt;   mkdir globe/jpt;
	rm -rf globe/js;    mkdir globe/js;
	rm -rf globe/xml;   mkdir globe/xml;

	wget http://bostonglobe.com/css/globe-fonts.css -O globe/css/globe-fonts.css;
	wget http://bostonglobe.com/css/globe-fonts.css.map -O globe/css/globe-fonts.css.map;

	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/BentonSans-Black/cd378061-6625-4ff0-8a52-906e943df050-2.eot -O globe/fonts/cd378061-6625-4ff0-8a52-906e943df050-2.eot;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/BentonSans-Black/cd378061-6625-4ff0-8a52-906e943df050-3.woff -O globe/fonts/cd378061-6625-4ff0-8a52-906e943df050-3.woff;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/BentonSans-Black/cd378061-6625-4ff0-8a52-906e943df050-1.ttf -O globe/fonts/cd378061-6625-4ff0-8a52-906e943df050-1.ttf;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/BentonSans-Black/cd378061-6625-4ff0-8a52-906e943df050-4.svg -O globe/fonts/cd378061-6625-4ff0-8a52-906e943df050-4.svg;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/BentonSans-Bold/79e52a98-c6b6-4ed0-a074-409e1de09fd6-2.eot -O globe/fonts/79e52a98-c6b6-4ed0-a074-409e1de09fd6-2.eot;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/BentonSans-Bold/79e52a98-c6b6-4ed0-a074-409e1de09fd6-3.woff -O globe/fonts/79e52a98-c6b6-4ed0-a074-409e1de09fd6-3.woff;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/BentonSans-Bold/79e52a98-c6b6-4ed0-a074-409e1de09fd6-1.ttf -O globe/fonts/79e52a98-c6b6-4ed0-a074-409e1de09fd6-1.ttf;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/BentonSans-Bold/79e52a98-c6b6-4ed0-a074-409e1de09fd6-4.svg -O globe/fonts/79e52a98-c6b6-4ed0-a074-409e1de09fd6-4.svg;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerHeadline/4d418a22-c167-4249-be16-b789d221d18d-2.eot -O globe/fonts/4d418a22-c167-4249-be16-b789d221d18d-2.eot;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerHeadline/4d418a22-c167-4249-be16-b789d221d18d-3.woff -O globe/fonts/4d418a22-c167-4249-be16-b789d221d18d-3.woff;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerHeadline/4d418a22-c167-4249-be16-b789d221d18d-1.ttf -O globe/fonts/4d418a22-c167-4249-be16-b789d221d18d-1.ttf;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerHeadline/4d418a22-c167-4249-be16-b789d221d18d-4.svg -O globe/fonts/4d418a22-c167-4249-be16-b789d221d18d-4.svg;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerHeadline-Bold/3c91bd2d-bc82-4bba-944e-ab157bcdeae2-2.eot -O globe/fonts/3c91bd2d-bc82-4bba-944e-ab157bcdeae2-2.eot;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerHeadline-Bold/3c91bd2d-bc82-4bba-944e-ab157bcdeae2-3.woff -O globe/fonts/3c91bd2d-bc82-4bba-944e-ab157bcdeae2-3.woff;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerHeadline-Bold/3c91bd2d-bc82-4bba-944e-ab157bcdeae2-1.ttf -O globe/fonts/3c91bd2d-bc82-4bba-944e-ab157bcdeae2-1.ttf;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerHeadline-Bold/3c91bd2d-bc82-4bba-944e-ab157bcdeae2-4.svg -O globe/fonts/3c91bd2d-bc82-4bba-944e-ab157bcdeae2-4.svg;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerGlobeHead-CondLarge/07ac6474-5c01-4c20-adf5-813ccbd172de-2.eot -O globe/fonts/07ac6474-5c01-4c20-adf5-813ccbd172de-2.eot;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerGlobeHead-CondLarge/07ac6474-5c01-4c20-adf5-813ccbd172de-3.woff -O globe/fonts/07ac6474-5c01-4c20-adf5-813ccbd172de-3.woff;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerGlobeHead-CondLarge/07ac6474-5c01-4c20-adf5-813ccbd172de-1.ttf -O globe/fonts/07ac6474-5c01-4c20-adf5-813ccbd172de-1.ttf;
	wget http://bostonglobe.com/rw/SysConfig/WebPortal/BostonGlobe/Framework/type/MillerGlobeHead-CondLarge/07ac6474-5c01-4c20-adf5-813ccbd172de-4.svg -O globe/fonts/07ac6474-5c01-4c20-adf5-813ccbd172de-4.svg;

	wget http://bostonglobe.com/Fragment/SysConfig/WebPortal/BostonGlobe/Framework/ajaxsamples/global-nav-menus.jpt -O globe/jpt/global-nav-menus.jpt;
	wget http://bostonglobe.com/Fragment/SysConfig/WebPortal/BostonGlobe/Framework/skins/leaf/story/most_viewed_right.jpt -O globe/jpt/most_viewed_right.jpt;
	wget http://bostonglobe.com/Fragment/SysConfig/WebPortal/BostonGlobe/Framework/skins/leaf/story/most_popular_right.jpt -O globe/jpt/most_popular_right.jpt;
	wget http://bostonglobe.com/Fragment/SysConfig/WebPortal/BostonGlobe/Framework/skins/leaf/story/most_comment_right.jpt -O globe/jpt/most_comment_right.jpt;
	wget http://bostonglobe.com/Fragment/SysConfig/WebPortal/BostonGlobe/Framework/frameset/header/weather-forecast.jpt -O globe/jpt/weather-forecast.jpt;

	wget http://bostonglobe.com/commons/js/portal.js -O globe/js/portal.js;

	wget http://bostonglobe.com/ugc/topics -O globe/xml/topics.xml;